/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corsifenwickcalculator;

/**
 *
 * @author Vincent
 */
public class CorsiForPanel extends javax.swing.JPanel {

    /**
     * Creates new form CorsiForPanel
     */
    public CorsiForPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shotsPane = new javax.swing.JPanel();
        shotsLbl = new javax.swing.JLabel();
        shotsPlusBtn = new javax.swing.JButton();
        shotsMinusBtn = new javax.swing.JButton();
        shotsTxtFld = new javax.swing.JTextField();
        blockedShotsPane = new javax.swing.JPanel();
        blockedShotsLbl = new javax.swing.JLabel();
        blockedShotsPlusBtn = new javax.swing.JButton();
        blockedShotsMinusBtn = new javax.swing.JButton();
        blockedShotsTxtFld = new javax.swing.JTextField();
        missedShotsPane = new javax.swing.JPanel();
        missedShotsLbl = new javax.swing.JLabel();
        missedShotsPlusBtn = new javax.swing.JButton();
        missedShotsMinusBtn = new javax.swing.JButton();
        missedShotsTxtFld = new javax.swing.JTextField();
        corsiPane = new javax.swing.JPanel();
        corsiLbl = new javax.swing.JLabel();
        corsiTxtFld = new javax.swing.JTextField();
        fenwickPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fenwickTxtFld = new javax.swing.JTextField();

        shotsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shotsLbl.setText("Shots");

        shotsPlusBtn.setText("+");
        shotsPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shotsPlusBtnActionPerformed(evt);
            }
        });

        shotsMinusBtn.setText("-");
        shotsMinusBtn.setMaximumSize(new java.awt.Dimension(41, 23));
        shotsMinusBtn.setMinimumSize(new java.awt.Dimension(41, 23));
        shotsMinusBtn.setPreferredSize(new java.awt.Dimension(41, 23));
        shotsMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shotsMinusBtnActionPerformed(evt);
            }
        });

        shotsTxtFld.setEditable(false);
        shotsTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        shotsTxtFld.setText("0");

        javax.swing.GroupLayout shotsPaneLayout = new javax.swing.GroupLayout(shotsPane);
        shotsPane.setLayout(shotsPaneLayout);
        shotsPaneLayout.setHorizontalGroup(
            shotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shotsPaneLayout.createSequentialGroup()
                .addGroup(shotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(shotsPaneLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(shotsTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(shotsPaneLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(shotsLbl))
                        .addGroup(shotsPaneLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(shotsPlusBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(shotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        shotsPaneLayout.setVerticalGroup(
            shotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shotsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shotsLbl)
                .addGap(11, 11, 11)
                .addGroup(shotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shotsPlusBtn)
                    .addComponent(shotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(shotsTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        blockedShotsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blockedShotsLbl.setText("Blocked Shots");

        blockedShotsPlusBtn.setText("+");
        blockedShotsPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockedShotsPlusBtnActionPerformed(evt);
            }
        });

        blockedShotsMinusBtn.setText("-");
        blockedShotsMinusBtn.setMaximumSize(new java.awt.Dimension(41, 23));
        blockedShotsMinusBtn.setMinimumSize(new java.awt.Dimension(41, 23));
        blockedShotsMinusBtn.setPreferredSize(new java.awt.Dimension(41, 23));
        blockedShotsMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockedShotsMinusBtnActionPerformed(evt);
            }
        });

        blockedShotsTxtFld.setEditable(false);
        blockedShotsTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        blockedShotsTxtFld.setText("0");

        javax.swing.GroupLayout blockedShotsPaneLayout = new javax.swing.GroupLayout(blockedShotsPane);
        blockedShotsPane.setLayout(blockedShotsPaneLayout);
        blockedShotsPaneLayout.setHorizontalGroup(
            blockedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockedShotsPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blockedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(blockedShotsTxtFld)
                    .addGroup(blockedShotsPaneLayout.createSequentialGroup()
                        .addComponent(blockedShotsPlusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockedShotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(blockedShotsPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(blockedShotsLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blockedShotsPaneLayout.setVerticalGroup(
            blockedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blockedShotsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockedShotsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(blockedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockedShotsPlusBtn)
                    .addComponent(blockedShotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(blockedShotsTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        missedShotsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        missedShotsLbl.setText("Missed Shots");

        missedShotsPlusBtn.setText("+");
        missedShotsPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missedShotsPlusBtnActionPerformed(evt);
            }
        });

        missedShotsMinusBtn.setText("-");
        missedShotsMinusBtn.setMaximumSize(new java.awt.Dimension(41, 23));
        missedShotsMinusBtn.setMinimumSize(new java.awt.Dimension(41, 23));
        missedShotsMinusBtn.setPreferredSize(new java.awt.Dimension(41, 23));
        missedShotsMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missedShotsMinusBtnActionPerformed(evt);
            }
        });

        missedShotsTxtFld.setEditable(false);
        missedShotsTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        missedShotsTxtFld.setText("0");

        javax.swing.GroupLayout missedShotsPaneLayout = new javax.swing.GroupLayout(missedShotsPane);
        missedShotsPane.setLayout(missedShotsPaneLayout);
        missedShotsPaneLayout.setHorizontalGroup(
            missedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missedShotsPaneLayout.createSequentialGroup()
                .addGroup(missedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(missedShotsPaneLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(missedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(missedShotsTxtFld)
                            .addGroup(missedShotsPaneLayout.createSequentialGroup()
                                .addComponent(missedShotsPlusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(missedShotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(missedShotsPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(missedShotsLbl)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        missedShotsPaneLayout.setVerticalGroup(
            missedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, missedShotsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(missedShotsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(missedShotsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missedShotsPlusBtn)
                    .addComponent(missedShotsMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(missedShotsTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        corsiLbl.setText("Corsi");

        corsiTxtFld.setEditable(false);
        corsiTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        corsiTxtFld.setText("0");

        javax.swing.GroupLayout corsiPaneLayout = new javax.swing.GroupLayout(corsiPane);
        corsiPane.setLayout(corsiPaneLayout);
        corsiPaneLayout.setHorizontalGroup(
            corsiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corsiPaneLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(corsiTxtFld)
                .addGap(11, 11, 11))
            .addGroup(corsiPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(corsiLbl)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        corsiPaneLayout.setVerticalGroup(
            corsiPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corsiPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(corsiLbl)
                .addGap(11, 11, 11)
                .addComponent(corsiTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        fenwickPane.setPreferredSize(new java.awt.Dimension(90, 93));

        jLabel1.setText("Fenwick");

        fenwickTxtFld.setEditable(false);
        fenwickTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fenwickTxtFld.setText("0");

        javax.swing.GroupLayout fenwickPaneLayout = new javax.swing.GroupLayout(fenwickPane);
        fenwickPane.setLayout(fenwickPaneLayout);
        fenwickPaneLayout.setHorizontalGroup(
            fenwickPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fenwickPaneLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(fenwickTxtFld)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fenwickPaneLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33))
        );
        fenwickPaneLayout.setVerticalGroup(
            fenwickPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fenwickPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(fenwickTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(shotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(blockedShotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(missedShotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(corsiPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(fenwickPane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockedShotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missedShotsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(corsiPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fenwickPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * This method is used to handle the actions of the minus button for the
     * missed shots panel.
     * When press, one is subtracted from missedShots, Corsi, and Fenwick
     * 
     * @param evt 
     */
    private void missedShotsMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missedShotsMinusBtnActionPerformed
        // TODO add your handling code here:
        String missedShotsString = missedShotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        String fenwickString = fenwickTxtFld.getText();
        int missedShots = Integer.parseInt(missedShotsString);
        int corsi = Integer.parseInt(corsiString);
        int fenwick = Integer.parseInt(fenwickString);
        missedShots--;
        corsi--;
        fenwick-- ;
        missedShotsString = Integer.toString(missedShots);
        corsiString = Integer.toString(corsi);
        fenwickString = Integer.toString(fenwick);
        missedShotsTxtFld.setText(missedShotsString);
        corsiTxtFld.setText(corsiString);
        fenwickTxtFld.setText(fenwickString);
    }//GEN-LAST:event_missedShotsMinusBtnActionPerformed
    /**
     * This method is used to handle the actions of the plus button of the shots
     * panel
     * When pressed, one is added to shots, Corsi, and Fenwick
     * @param evt 
     */
    private void shotsPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shotsPlusBtnActionPerformed
        // TODO add your handling code here:
        String shotsString = shotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        String fenwickString= fenwickTxtFld.getText();
        int shots = Integer.parseInt(shotsString);
        int corsi = Integer.parseInt(corsiString);
        int fenwick = Integer.parseInt(fenwickString);
        shots++;
        corsi++;
        fenwick++;
        shotsString = Integer.toString(shots);
        corsiString = Integer.toString(corsi);
        fenwickString = Integer.toString(fenwick);
        shotsTxtFld.setText(shotsString);
        corsiTxtFld.setText(corsiString);
        fenwickTxtFld.setText(fenwickString);
    }//GEN-LAST:event_shotsPlusBtnActionPerformed
    /**
     * 
     * This method is used to handle the actions of the plus button in the 
     * blocked shots panel
     * When pressed, one is added to blocked shots and Corsi
     * @param evt 
     */
    private void blockedShotsPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockedShotsPlusBtnActionPerformed
        // TODO add your handling code here:
        String blockedShotsString = blockedShotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        int blockedShots = Integer.parseInt(blockedShotsString);
        int corsi = Integer.parseInt(corsiString);
        blockedShots++;
        corsi++;
        blockedShotsString = Integer.toString(blockedShots);
        corsiString = Integer.toString(corsi);
        blockedShotsTxtFld.setText(blockedShotsString);
        corsiTxtFld.setText(corsiString);
    }//GEN-LAST:event_blockedShotsPlusBtnActionPerformed
    /**
     * This method is used to handle the actions of the plus button in the 
     * missed shots panel
     * When pressed, one is added to missed shots, Corsi, and Fenwick
     * @param evt 
     */
    private void missedShotsPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missedShotsPlusBtnActionPerformed
        // TODO add your handling code here:
        String missedShotsString = missedShotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        String fenwickString = fenwickTxtFld.getText();
        int missedShots = Integer.parseInt(missedShotsString);
        int corsi = Integer.parseInt(corsiString);
        int fenwick = Integer.parseInt(fenwickString);
        missedShots++;
        corsi++;
        fenwick++;
        missedShotsString = Integer.toString(missedShots);
        corsiString = Integer.toString(corsi);
        fenwickString = Integer.toString(fenwick);
        missedShotsTxtFld.setText(missedShotsString);
        corsiTxtFld.setText(corsiString);
        fenwickTxtFld.setText(fenwickString);
    }//GEN-LAST:event_missedShotsPlusBtnActionPerformed
    /**
     * This method is used to handle the actions of the minus button in the
     * blocked shots panel
     * When pressed, one is subtracted from blocked shots and Corsi
     * @param evt 
     */
    private void blockedShotsMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockedShotsMinusBtnActionPerformed
        // TODO add your handling code here:
        String blockedShotsString = blockedShotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        int blockedShots = Integer.parseInt(blockedShotsString);
        int corsi = Integer.parseInt(corsiString);
        blockedShots--;
        corsi--;
        blockedShotsString = Integer.toString(blockedShots);
        corsiString = Integer.toString(corsi);
        blockedShotsTxtFld.setText(blockedShotsString);
        corsiTxtFld.setText(corsiString);
    }//GEN-LAST:event_blockedShotsMinusBtnActionPerformed
    /**
     * This method is used to handle the actions of the minus button in the
     * shots panel
     * When pressed, one is subtracted from shots, Corsi, and Fenwick
     * @param evt 
     */
    private void shotsMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shotsMinusBtnActionPerformed
        // TODO add your handling code here:
        String shotsString = shotsTxtFld.getText();
        String corsiString = corsiTxtFld.getText();
        String fenwickString= fenwickTxtFld.getText();
        int shots = Integer.parseInt(shotsString);
        int corsi = Integer.parseInt(corsiString);
        int fenwick = Integer.parseInt(fenwickString);
        shots--;
        corsi--;
        fenwick--;
        shotsString = Integer.toString(shots);
        corsiString = Integer.toString(corsi);
        fenwickString = Integer.toString(fenwick);
        shotsTxtFld.setText(shotsString);
        corsiTxtFld.setText(corsiString);
        fenwickTxtFld.setText(fenwickString);        
    }//GEN-LAST:event_shotsMinusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blockedShotsLbl;
    private javax.swing.JButton blockedShotsMinusBtn;
    private javax.swing.JPanel blockedShotsPane;
    private javax.swing.JButton blockedShotsPlusBtn;
    private javax.swing.JTextField blockedShotsTxtFld;
    private javax.swing.JLabel corsiLbl;
    private javax.swing.JPanel corsiPane;
    private javax.swing.JTextField corsiTxtFld;
    private javax.swing.JPanel fenwickPane;
    private javax.swing.JTextField fenwickTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel missedShotsLbl;
    private javax.swing.JButton missedShotsMinusBtn;
    private javax.swing.JPanel missedShotsPane;
    private javax.swing.JButton missedShotsPlusBtn;
    private javax.swing.JTextField missedShotsTxtFld;
    private javax.swing.JLabel shotsLbl;
    private javax.swing.JButton shotsMinusBtn;
    private javax.swing.JPanel shotsPane;
    private javax.swing.JButton shotsPlusBtn;
    private javax.swing.JTextField shotsTxtFld;
    // End of variables declaration//GEN-END:variables
}
